### ISSUE TITLE
A short question about  initial search range.

### ISSUE THREAD

**Issue by daya0576** [DBWangGroupUNSW/COMP6714#2]
**Dear Prof Wang, thanks for ur well designed exercise, really enjoy it. 
The only question is the initial search range.** 

**In the lecture slide, the initial search range is 1:**
## ![image](https://cloud.githubusercontent.com/assets/6239652/17429391/d63f151a-5b31-11e6-8f71-3e9253940ffd.png)

<br>
**So I get this result:** 
jump from pos 0->1->3->7->15
## ![image](https://cloud.githubusercontent.com/assets/6239652/17428966/5ee32e72-5b2f-11e6-92ad-423bb63e60b8.png)

<br>
**But if I set my initial search range to 2, I get the same result as u:** 
jupm from pos 0->2->6->14

**So does it mean the initial search range dose not really matter and can be defined by yourself? Is it right?**

**Comment by DBWangWei** [comment]
I looked into my code and you are right -- I started from inc = 2 (see the solution I released). 

btw, can you post such discussions in the piazza forum instead, so that other students in the class can also see. As I understand, not all students uses github, and the forum also allow students collaborate with each other. 

Wei

**Comment by daya0576** [comment]
Sure, a bit shy to post something in the forum, but I will do that if I has any other question.

**Comment by DBWangWei** [comment]
Post it anonymously, :p

and thanks for following up with the notebooks - I am creating new ones 
this semester and there will still be errors like you've found so far.

Wei
